package com.ai.free.model;

// Generated 2014-8-7 10:15:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AnthorInfo generated by hbm2java
 */
@SuppressWarnings("serial")
public class AnthorInfo implements java.io.Serializable {

	private long authorid;
	private String authorname;
	private String realname;
	private Date birthday;
	private String notes;

	public AnthorInfo() {
	}

	public AnthorInfo(long authorid, String authorname, String realname) {
		this.authorid = authorid;
		this.authorname = authorname;
		this.realname = realname;
	}

	public AnthorInfo(long authorid, String authorname, String realname,
			Date birthday, String notes) {
		this.authorid = authorid;
		this.authorname = authorname;
		this.realname = realname;
		this.birthday = birthday;
		this.notes = notes;
	}

	public long getAuthorid() {
		return this.authorid;
	}

	public void setAuthorid(long authorid) {
		this.authorid = authorid;
	}

	public String getAuthorname() {
		return this.authorname;
	}

	public void setAuthorname(String authorname) {
		this.authorname = authorname;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
