package com.ai.free.model;

// Generated 2014-7-30 18:19:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EcoMenu generated by hbm2java
 */
@SuppressWarnings("serial")
public class EcoMenu implements java.io.Serializable {

	private long menuid;
	private String menuname;
	private String notes;
	private String menuurl;
	private long parentmenuid;
	private Short sortid;
	private boolean isused;
	private Date donedate;
	private String state;

	public EcoMenu() {
	}

	public EcoMenu(long menuid, String menuname, String notes,
			long parentmenuid, boolean isused) {
		this.menuid = menuid;
		this.menuname = menuname;
		this.notes = notes;
		this.parentmenuid = parentmenuid;
		this.isused = isused;
	}

	public EcoMenu(long menuid, String menuname, String notes, String menuurl,
			long parentmenuid, Short sortid, boolean isused, Date donedate,
			String state) {
		this.menuid = menuid;
		this.menuname = menuname;
		this.notes = notes;
		this.menuurl = menuurl;
		this.parentmenuid = parentmenuid;
		this.sortid = sortid;
		this.isused = isused;
		this.donedate = donedate;
		this.state = state;
	}

	public long getMenuid() {
		return this.menuid;
	}

	public void setMenuid(long menuid) {
		this.menuid = menuid;
	}

	public String getMenuname() {
		return this.menuname;
	}

	public void setMenuname(String menuname) {
		this.menuname = menuname;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getMenuurl() {
		return this.menuurl;
	}

	public void setMenuurl(String menuurl) {
		this.menuurl = menuurl;
	}

	public long getParentmenuid() {
		return this.parentmenuid;
	}

	public void setParentmenuid(long parentmenuid) {
		this.parentmenuid = parentmenuid;
	}

	public Short getSortid() {
		return this.sortid;
	}

	public void setSortid(Short sortid) {
		this.sortid = sortid;
	}

	public boolean isIsused() {
		return this.isused;
	}

	public void setIsused(boolean isused) {
		this.isused = isused;
	}

	public Date getDonedate() {
		return this.donedate;
	}

	public void setDonedate(Date donedate) {
		this.donedate = donedate;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
