package com.ai.free.model;

// Generated 2014-7-9 22:24:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TUser generated by hbm2java
 */
@SuppressWarnings("serial")
public class TUser implements java.io.Serializable {

	private String initid;
	private String username;
	private String password;
	private String nickname;
	private Date born;

	public TUser() {
	}

	public TUser(String initid) {
		this.initid = initid;
	}

	public TUser(String initid, String username, String password,
			String nickname, Date born) {
		this.initid = initid;
		this.username = username;
		this.password = password;
		this.nickname = nickname;
		this.born = born;
	}

	public String getInitid() {
		return this.initid;
	}

	public void setInitid(String initid) {
		this.initid = initid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public Date getBorn() {
		return this.born;
	}

	public void setBorn(Date born) {
		this.born = born;
	}

}
